SET INSTALLUTILFILEPATH=C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\InstallUtil.exe

SET SERVICEDIRECTORYPATH=C:\Program Files\ParentalControl\ParentalControlWinService\bin
SET SERVICEFILENAME=ParentalControl.WinService.WinServiceApp.exe

SET SERVICEFILEPATH=%SERVICEDIRECTORYPATH%\%SERVICEFILENAME%
del /F /Q "%SERVICEDIRECTORYPATH%\*.InstallLog"	
del /F /Q "%SERVICEDIRECTORYPATH%\*.InstallState"
%INSTALLUTILFILEPATH% "%SERVICEFILEPATH%"
